spring:
  application:
    name: register-center
  security:
       user:
         name: admin
         password: 123
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://admin:123@cluster1:9001/eureka/,http://admin:123@cluster3:9003/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: cluster2